[package]
name = "seloria-mempool"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
seloria-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
